services:
  yaf:
    build: ./yaf
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - super_mediator

  super_mediator:
    build: ./super_mediator
    restart: always
    ports:
      - 18000:18000
    depends_on:
      - ipfix-load-balancer

  ipfix-load-balancer:
    build: ./ipfix-load-balancer
    restart: always
    ports:
      - 18500:18500
    depends_on:
      - malfix

  malfix:
    build: ./malfix
    restart: always
    ports:
      - "19000-19100:19000-19100"
    volumes:
      - malfix:/root/.maltrail
    depends_on:
      - goflow2
 
  goflow2:
    build: ./goflow2
    restart: always
    ports:
      - 2055:2055/udp
    depends_on:
      - kafka

  kafka:
    image: apache/kafka:3.7.0
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=3

  geo-anomaly-detection:
    build: ./additional/geo-anomaly-detection
    restart: always
    depends_on:
      - kafka

volumes:
  malfix:
